In [1]:
import pickle
import pandas as pd

import os, sys
import numpy as np
import networkx as nx
import seaborn as sns
import scipy.stats as ss
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import TwoSlopeNorm
from os.path import expanduser

sys.path.insert(1, os.path.join(sys.path[0], '..'))
import data_misc as dm
import model_misc as mm
import plot_misc as pm

In [84]:
# eventname, dataname = 'CNS_calls.evt', 'Copenhagen_nets'
# eventname, dataname = 'CNS_sms.evt', 'Copenhagen_nets'
# eventname, dataname = 'CollegeMsg.evt', 'SNAP'
# eventname, dataname = 'email_Eu_core.evt', 'SNAP'
# eventname, dataname = 'email.evt', 'greedy_walk_nets'
# eventname, dataname = 'forum.evt', 'greedy_walk_nets'
# eventname, dataname = 'messages.evt', 'greedy_walk_nets'
# eventname, dataname = 'pok.evt', 'greedy_walk_nets'
# eventname, dataname = 'Enron.evt', 'Enron'
# eventname, dataname = 'fb.evt', 'greedy_walk_nets'
# eventname, dataname = 'MPC_Wu_SD01.evt', 'SMS_net'
# eventname, dataname = 'MPC_Wu_SD02.evt', 'SMS_net'
# eventname, dataname = 'MPC_Wu_SD03.evt', 'SMS_net'

# eventname, dataname = 'contact.evt', 'offline_nets'
# eventname, dataname = 'sp_hospital.evt', 'offline_nets'
# eventname, dataname = 'sp_colocation_LH10.evt', 'offline_nets'
# eventname, dataname = 'sp_colocation_InVS13.evt', 'offline_nets'
eventname, dataname = 'sp_colocation_Thiers13.evt', 'offline_nets'
# eventname, dataname = 'sp_high_school_new_2011.evt', 'offline_nets'
# eventname, dataname = 'sp_office.evt', 'offline_nets'
# eventname, dataname = 'sp_high_school_new_2012.evt', 'offline_nets'
# eventname, dataname = 'sp_hypertext_contacts.evt', 'offline_nets'

root_data = '../temporal_networks/'

saveloc = './files/data/'

In [85]:
savename = f'{root_data}/{dataname}/data_formatted/{eventname}'
events = pd.read_csv(savename, sep=';', header=None)
savename

'../temporal_networks//offline_nets/data_formatted/sp_colocation_Thiers13.evt'

In [86]:
events

           0    1       2
0          1  313  202760
1          1  313  202760
2          1  313  202760
3          1  313  202760
4          1  313  202760
...      ...  ...     ...
3688546  311  326  229480
3688547  311  326  229760
3688548  311  326  230200
3688549  311  326  230920
3688550  311  326  231160

[3688551 rows x 3 columns]

In [87]:
# datasets = [
#                 ('Copenhagen_nets', 'CNS_calls.evt'),
#                 ('Copenhagen_nets', 'CNS_sms.evt'),
#                 ('Enron', 'Enron.evt'),
#                 ('greedy_walk_nets', 'email.evt'),
#                 ('greedy_walk_nets', 'eml2.evt'),
#                 ('greedy_walk_nets', 'fb.evt'),
#                 ('greedy_walk_nets', 'forum.evt'),
#                 ('greedy_walk_nets', 'messages.evt'),
#                 ('greedy_walk_nets', 'pok.evt'),
#                 ('SMS_net', 'MPC_Wu_SD01.evt'),
#                 ('SMS_net', 'MPC_Wu_SD02.evt'),
#                 ('SMS_net', 'MPC_Wu_SD03.evt'),
#                 ('SNAP', 'email_Eu_core.evt'),
#                 ('SNAP', 'CollegeMsg.evt'),
#                 ('offline_nets', 'sp_hospital.evt'),
#                 ('offline_nets', 'sp_colocation_LH10.evt'),
#                 ('offline_nets', 'sp_office.evt'),
#                 ('offline_nets', 'sp_colocation_InVS13.evt'),
#                 ('offline_nets', 'sp_colocation_InVS15.evt'),
#                 ('offline_nets', 'sp_primary_school.evt'),
#                 ('offline_nets', 'sp_colocation_LyonSchool.evt'),
#                 ('offline_nets', 'sp_high_school_new_2011.evt'),
#                 ('offline_nets', 'sp_high_school_new_2012.evt'),
#                 ('offline_nets', 'sp_colocation_Thiers13.evt'),
#                 ('offline_nets', 'sp_high_school_proximity.evt'),
#                 ('offline_nets', 'reality_mining.evt'),
#                 ('offline_nets', 'contact.evt'),
#                 ('offline_nets', 'sp_colocation_SFHH.evt'),
#                 ('offline_nets', 'sp_hypertext_contacts.evt'),
#                 ('offline_nets', 'sp_infectious.evt')
#             ]

In [88]:
# datasets = [
#                 ('Copenhagen_nets', 'CNS_calls.evt'),
#                 ('Copenhagen_nets', 'CNS_sms.evt'),
#                 ('Enron', 'Enron.evt'),
#                 ('greedy_walk_nets', 'email.evt'),
#                 ('greedy_walk_nets', 'eml2.evt'),
#                 ('greedy_walk_nets', 'fb.evt'),
#                 ('greedy_walk_nets', 'forum.evt'),
#                 ('greedy_walk_nets', 'messages.evt'),
#                 ('greedy_walk_nets', 'pok.evt'),
#                 ('SMS_net', 'MPC_Wu_SD01.evt'),
#                 ('SMS_net', 'MPC_Wu_SD02.evt'),
#                 ('SMS_net', 'MPC_Wu_SD03.evt'),
#                 ('SNAP', 'email_Eu_core.evt'),
#                 ('SNAP', 'CollegeMsg.evt')
#             ]

# dm.data_params( datasets, root_data, 'n', saveloc )

In [89]:
dm.egonet_props_acts_pieces( dataname, eventname, root_data, 'n', saveloc )

./files/data/egonet_props_pieces_sp_colocation_Thiers13.pkl
./files/data/egonet_acts_pieces_sp_colocation_Thiers13.pkl

/Users/pkt949/Downloads/offline_egonets_C72h-main/Farsignatures-master/data_misc.py:125: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  amins = egonet_acts.groupby('nodei').apply( min )
/Users/pkt949/Downloads/offline_egonets_C72h-main/Farsignatures-master/data_misc.py:126: FutureWarning: The provided callable <built-in function max> is currently using np.maximum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.maximum.reduce instead.
  amaxs = egonet_acts.groupby('nodei').apply( max )
/Users/pkt949/Downloads/offline_egonets_C72h-main/Farsignatures-master/data_misc.py:125: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  amins = egonet_acts.groupby('nodei').apply( min )
/Users/pkt949/Downloads/offline_egonets_C72h-main/Farsignatures-master/data_misc.py:126: FutureWarning: The provided callable <built-in function max> is currently using np.maximum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.maximum.reduce instead.
  amaxs = egonet_acts.groupby('nodei').apply( max )

([       degree  strength     act_avg  act_min  act_max
  nodei
  0          28      5495  196.250000       12      706
  1          55     15917  289.400000        1     1475
  2          57     10147  178.017544        1      585
  3          41     10149  247.536585        1      662
  4          53      2893   54.584906        5      340
  ...       ...       ...         ...      ...      ...
  322        68     12351  181.632353       11      795
  323        60     11742  195.700000        9      723
  324        84     19385  230.773810        1      619
  325        79     26834  339.670886       10     2080
  326        64     11100  173.437500        5      939

  [327 rows x 5 columns],
         degree  strength     act_avg  act_min  act_max
  nodei
  0          29      5494  189.448276        4      550
  1          59     15916  269.762712        2     1730
  2          55     10147  184.490909        1      623
  3          65     10149  156.138462       10      556
  4          51      2892   56.705882       11      275
  ...       ...       ...         ...      ...      ...
  322        76     12351  162.513158        1      399
  323        67     11741  175.238806        2      582
  324        88     19384  220.272727        1      514
  325        79     26833  339.658228        1     2042
  326        75     11099  147.986667        1      471

  [327 rows x 5 columns]],
 [nodei  nodej
  0      33       278
         44        19
         51       392
         56        77
         69       381
                 ...
  326    321      149
         322      135
         323      124
         324      227
         325      153
  Length: 19836, dtype: int64,
  nodei  nodej
  0      33       151
         44        22
         56       300
         67        16
         69       208
                 ...
  326    321      195
         322      103
         323      127
         324      387
         325      199
  Length: 20712, dtype: int64])

In [90]:
dm.egonet_fits_piece( dataname, eventname, 0, root_data, 'n', saveloc, alpha_bounds=(1e-4, 1e3), nsims=2500 )

./files/data/egonet_props_pieces_sp_colocation_Thiers13.pkl
./files/data/egonet_acts_pieces_sp_colocation_Thiers13.pkl
ego 0 out of 327
ego 10 out of 327
ego 20 out of 327
ego 30 out of 327
ego 40 out of 327
ego 50 out of 327
ego 60 out of 327
ego 70 out of 327
ego 80 out of 327
ego 90 out of 327
ego 100 out of 327
ego 110 out of 327
ego 120 out of 327
ego 130 out of 327
ego 140 out of 327
ego 150 out of 327
ego 160 out of 327
ego 170 out of 327
ego 180 out of 327
ego 190 out of 327
ego 200 out of 327
ego 210 out of 327
ego 220 out of 327
ego 230 out of 327
ego 240 out of 327
ego 250 out of 327
ego 260 out of 327
ego 270 out of 327
ego 280 out of 327
ego 290 out of 327
ego 300 out of 327
ego 310 out of 327
ego 320 out of 327

measure,alpha,KS_stat,KS_pval,W2_stat,W2_pval,U2_stat,U2_pval,A2_stat,A2_pval
nodei,,,,,,,,,
0,-10.851635,0.125374,0.7016,0.085300,0.6364,0.053668,0.5648,0.655654,0.7636
1,-0.403486,0.102941,0.3504,0.066355,0.6100,0.064803,0.4092,0.905315,0.2660
2,-0.305678,0.147137,0.0996,0.326126,0.0440,0.158589,0.0648,2.083802,0.0488
3,-0.025859,0.153049,0.3064,0.304665,0.1244,0.087921,0.3636,1.961968,0.1396
4,-3.988047,0.375785,0.0000,1.512920,0.0000,1.381215,0.0000,7.307184,0.0000
...,...,...,...,...,...,...,...,...,...
322,-9.929707,0.163958,0.0044,0.321011,0.0096,0.315235,0.0004,1.540079,0.0272
323,-7.962514,0.162076,0.0188,0.152970,0.2320,0.100239,0.1712,0.871001,0.3608
324,-0.234605,0.219900,0.0000,1.182324,0.0000,0.614482,0.0000,6.912884,0.0000
325,-9.439027,0.060191,0.8124,0.060700,0.5968,0.059469,0.4464,0.550675,0.5320
326,-4.100541,0.189273,0.0016,0.325915,0.0040,0.306912,0.0000,1.484417,0.0212

In [ ]:
dm.egonet_fits_piece( dataname, eventname, 1, root_data, 'n', saveloc, alpha_bounds=(1e-4, 1e3), nsims=2500 )

./files/data/egonet_props_pieces_sp_colocation_Thiers13.pkl
./files/data/egonet_acts_pieces_sp_colocation_Thiers13.pkl
ego 0 out of 327

ego 10 out of 327
ego 20 out of 327
ego 30 out of 327
ego 40 out of 327
ego 50 out of 327
ego 60 out of 327
ego 70 out of 327
ego 80 out of 327
ego 90 out of 327
ego 100 out of 327

In [ ]:
dm.egonet_props_acts( dataname, eventname, root_data, 'n', saveloc )

/Users/pkt949/Downloads/offline_egonets_C72h-main/Farsignatures-master/data_misc.py:60: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  amins = egonet_acts_grouped.apply( min )
/Users/pkt949/Downloads/offline_egonets_C72h-main/Farsignatures-master/data_misc.py:61: FutureWarning: The provided callable <built-in function max> is currently using np.maximum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.maximum.reduce instead.
  amaxs = egonet_acts_grouped.apply( max )

(       degree  strength     act_avg       act_var  act_min  act_max
 nodei
 0           8       611   76.375000  17364.553571       10      400
 1           4        77   19.250000     74.250000       10       28
 2           2        51   25.500000     84.500000       19       32
 3           5       497   99.400000  11196.800000       11      283
 4           3        61   20.333333     46.333333       15       28
 ...       ...       ...         ...           ...      ...      ...
 164        11       551   50.090909   1802.690909       10      132
 165        10       623   62.300000   4230.233333       10      214
 166         3       201   67.000000   1791.000000       22      106
 167        13       824   63.384615   6054.423077       11      272
 168        12      1592  132.666667  42699.878788       13      740

 [169 rows x 6 columns],
 nodei  nodej
 0      7         52
        8         20
        11       400
        28        51
        45        10
                ...
 168    154      199
        156       58
        160      740
        165      102
        167       85
 Length: 966, dtype: int64)

In [ ]:
loadflag = 'n' # to create them, loadflag = 'n', otherwise 'y'

In [ ]:
dm.egonet_kernel( dataname, eventname, root_data, loadflag, saveloc )

ego 0 out of 169
ego 100 out of 169
<class 'pandas.core.indexes.base.Index'>

(0, 0)        0.011142
(0, 1)        0.133333
(0, 2)        0.063492
(0, 3)        0.333333
(0, 4)        0.888889
                ...
(168, 736)    1.000000
(168, 737)    1.000000
(168, 738)    1.000000
(168, 739)    1.000000
(168, 740)    0.000000
Length: 27935, dtype: float64

In [ ]:
dm.egonet_jaccard( eventname, loadflag, saveloc, nodei='nodei', nodej='nodej', saveflag=True )

nodei
0      1.000000
1      0.750000
2      1.000000
3      0.400000
4      0.666667
         ...
164    0.909091
165    0.900000
166    0.666667
167    0.923077
168    0.666667
Length: 169, dtype: float64

In [ ]:
dm.egonet_fits( dataname, eventname, root_data, loadflag, saveloc, egonet_tuple=None, alpha_bounds=(1e-4, 1e3), nsims=2500)

ego 0 out of 169
ego 10 out of 169
ego 20 out of 169
ego 30 out of 169
ego 40 out of 169
ego 50 out of 169
ego 60 out of 169
ego 70 out of 169
ego 80 out of 169
ego 90 out of 169
ego 100 out of 169
ego 110 out of 169
ego 120 out of 169
ego 130 out of 169
ego 140 out of 169
ego 150 out of 169
ego 160 out of 169

measure,alpha,KS_stat,KS_pval,W2_stat,W2_pval,U2_stat,U2_pval,A2_stat,A2_pval
nodei,,,,,,,,,
0,-9.590201,0.256093,0.3784,0.086931,0.4592,0.085518,0.2288,1.117187,0.4244
1,-9.260580,0.424769,0.1416,0.153721,0.1900,0.081507,0.2492,1.521371,0.1316
2,-18.728540,0.486682,0.0000,0.087876,0.2720,0.053704,0.5288,1.569635,0.0000
3,-10.535089,0.378243,0.3044,0.137036,0.3584,0.096366,0.2444,1.555023,0.3952
4,-14.432697,0.316641,0.3268,0.061497,0.3996,0.038397,0.3996,0.911491,0.2636
...,...,...,...,...,...,...,...,...,...
164,-9.258634,0.165168,0.8188,0.047087,0.8732,0.024358,0.9672,0.838307,0.6076
165,-9.520354,0.223199,0.4272,0.095013,0.4256,0.084961,0.2512,0.896222,0.5208
166,-21.676661,0.557842,0.1284,0.210272,0.1448,0.125681,0.1408,2.444367,0.0868
167,-10.455437,0.198973,0.3652,0.107396,0.3020,0.106247,0.1200,0.882775,0.4200
168,-12.717082,0.188398,0.4904,0.065875,0.5428,0.053634,0.5108,0.787603,0.6400